#ifndef TELEOP_TYPES_READER_H
#define TELEOP_TYPES_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

typedef struct getugo_Header getugo_Header_t;
typedef const getugo_Header_t *getugo_Header_struct_t;
typedef getugo_Header_t *getugo_Header_mutable_struct_t;
typedef const getugo_Header_t *getugo_Header_vec_t;
typedef getugo_Header_t *getugo_Header_mutable_vec_t;

typedef const struct getugo_EgoPose_table *getugo_EgoPose_table_t;
typedef struct getugo_EgoPose_table *getugo_EgoPose_mutable_table_t;
typedef const flatbuffers_uoffset_t *getugo_EgoPose_vec_t;
typedef flatbuffers_uoffset_t *getugo_EgoPose_mutable_vec_t;
typedef const struct getugo_Ping_table *getugo_Ping_table_t;
typedef struct getugo_Ping_table *getugo_Ping_mutable_table_t;
typedef const flatbuffers_uoffset_t *getugo_Ping_vec_t;
typedef flatbuffers_uoffset_t *getugo_Ping_mutable_vec_t;
typedef const struct getugo_Pong_table *getugo_Pong_table_t;
typedef struct getugo_Pong_table *getugo_Pong_mutable_table_t;
typedef const flatbuffers_uoffset_t *getugo_Pong_vec_t;
typedef flatbuffers_uoffset_t *getugo_Pong_mutable_vec_t;
typedef const struct getugo_CameraRequest_table *getugo_CameraRequest_table_t;
typedef struct getugo_CameraRequest_table *getugo_CameraRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *getugo_CameraRequest_vec_t;
typedef flatbuffers_uoffset_t *getugo_CameraRequest_mutable_vec_t;
#ifndef getugo_Header_identifier
#define getugo_Header_identifier flatbuffers_identifier
#endif
#define getugo_Header_type_hash ((flatbuffers_thash_t)0x1b5c43f)
#define getugo_Header_type_identifier "\x3f\xc4\xb5\x01"
#ifndef getugo_EgoPose_identifier
#define getugo_EgoPose_identifier flatbuffers_identifier
#endif
#define getugo_EgoPose_type_hash ((flatbuffers_thash_t)0xbcc6df36)
#define getugo_EgoPose_type_identifier "\x36\xdf\xc6\xbc"
#ifndef getugo_Ping_identifier
#define getugo_Ping_identifier flatbuffers_identifier
#endif
#define getugo_Ping_type_hash ((flatbuffers_thash_t)0x4589dcc6)
#define getugo_Ping_type_identifier "\xc6\xdc\x89\x45"
#ifndef getugo_Pong_identifier
#define getugo_Pong_identifier flatbuffers_identifier
#endif
#define getugo_Pong_type_hash ((flatbuffers_thash_t)0x4114f6bc)
#define getugo_Pong_type_identifier "\xbc\xf6\x14\x41"
#ifndef getugo_CameraRequest_identifier
#define getugo_CameraRequest_identifier flatbuffers_identifier
#endif
#define getugo_CameraRequest_type_hash ((flatbuffers_thash_t)0x35c668ba)
#define getugo_CameraRequest_type_identifier "\xba\x68\xc6\x35"


struct getugo_Header {
    alignas(8) int64_t timestamp;
};
static_assert(sizeof(getugo_Header_t) == 8, "struct size mismatch");

static inline const getugo_Header_t *getugo_Header__const_ptr_add(const getugo_Header_t *p, size_t i) { return p + i; }
static inline getugo_Header_t *getugo_Header__ptr_add(getugo_Header_t *p, size_t i) { return p + i; }
static inline getugo_Header_struct_t getugo_Header_vec_at(getugo_Header_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t getugo_Header__size(void) { return 8; }
static inline size_t getugo_Header_vec_len(getugo_Header_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(getugo_Header)

__flatbuffers_define_struct_scalar_field(getugo_Header, timestamp, flatbuffers_int64, int64_t)


struct getugo_EgoPose_table { uint8_t unused__; };

static inline size_t getugo_EgoPose_vec_len(getugo_EgoPose_vec_t vec)
__flatbuffers_vec_len(vec)
static inline getugo_EgoPose_table_t getugo_EgoPose_vec_at(getugo_EgoPose_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(getugo_EgoPose_table_t, vec, i, 0)
__flatbuffers_table_as_root(getugo_EgoPose)

__flatbuffers_define_scalar_field(0, getugo_EgoPose, latitude, flatbuffers_double, double, 0.000000)
__flatbuffers_define_scalar_field(1, getugo_EgoPose, longitude, flatbuffers_double, double, 0.000000)
__flatbuffers_define_scalar_field(2, getugo_EgoPose, heading, flatbuffers_float, float, 0.000000f)

struct getugo_Ping_table { uint8_t unused__; };

static inline size_t getugo_Ping_vec_len(getugo_Ping_vec_t vec)
__flatbuffers_vec_len(vec)
static inline getugo_Ping_table_t getugo_Ping_vec_at(getugo_Ping_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(getugo_Ping_table_t, vec, i, 0)
__flatbuffers_table_as_root(getugo_Ping)


struct getugo_Pong_table { uint8_t unused__; };

static inline size_t getugo_Pong_vec_len(getugo_Pong_vec_t vec)
__flatbuffers_vec_len(vec)
static inline getugo_Pong_table_t getugo_Pong_vec_at(getugo_Pong_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(getugo_Pong_table_t, vec, i, 0)
__flatbuffers_table_as_root(getugo_Pong)


struct getugo_CameraRequest_table { uint8_t unused__; };

static inline size_t getugo_CameraRequest_vec_len(getugo_CameraRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline getugo_CameraRequest_table_t getugo_CameraRequest_vec_at(getugo_CameraRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(getugo_CameraRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(getugo_CameraRequest)

__flatbuffers_define_scalar_field(0, getugo_CameraRequest, camera_id, flatbuffers_int8, int8_t, INT8_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* TELEOP_TYPES_READER_H */
